# Generated by Django 5.0.1 on 2024-02-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SUMMER', 'Summer'), ('WINTER', 'Winter'), ('MONSOON', 'Monsoon'), ('OTHERS', 'Others')], max_length=10, null=True),
        ),
    ]
